### ISSUE TITLE
Wording suggestion 

### ISSUE THREAD

**Issue by adshaikh** [TypeNetwork/variable-fonts-info-site#103]
Link: https://variablefonts.typenetwork.com/topics/animation/variations
Original text seems to be missing a verb...
"Doing this simply supported in most browsers."

**Comment by dberlow** [comment]
Thanks, that’s very helpful.

Chris, this is corrected at:
https://github.com/TypeNetwork/variable-fonts-info-site/blob/master/topics/animation/variations.md

And I found a space after comma missing and corrected that at:
https://github.com/TypeNetwork/variable-fonts-info-site/blob/master/topics/animation/index.md


On Jun 24, 2019, at 8:17 PM, adshaikh <notifications@github.com> wrote:

Link: https://variablefonts.typenetwork.com/topics/animation/variations
Original text seems to be missing a verb...
"Doing this simply supported in most browsers."

**Comment by chrissam42** [comment]
Thank you, fixed in c952029a3bb7c7245d73f5b689ad059b7c4b94ab
