### ISSUE TITLE
Aa animation

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/variable-fonts-info-site#104]
At the end of https://variablefonts.typenetwork.com/topics/styles/variations

The little animation of Aa, is not as good, (serifs of A), or and smooth animating, as it could be.

Can this be a CSS movie that works better?

**Comment by chrissam42** [comment]
The serif thing is a Safari rendering wrinkle, as far as I can tell. I tried the same animation outside of the SVG and the same thing happened.

I’d be happy to adjust the animation parameters. So, slower transitions, check. Do you want it to pause at each step or just keep smoothly flowing through?

**Comment by chrissam42** [comment]
Also the Aa position is too high in Firefox, will fix.

**Comment by dberlow** [comment]
Smooth and continuous will be fine.

On Jun 28, 2019, at 7:48 AM, Chris Lewis <notifications@github.com> wrote:

The serif thing is a Safari rendering wrinkle, as far as I can tell. I tried the same animation outside of the SVG and the same thing happened.

I’d be happy to adjust the animation parameters. So, slower transitions, check. Do you want it to pause at each step or just keep smoothly flowing through?
