### ISSUE TITLE
roboto-instances-vs-interpolated uses opsz when it isn't in the font

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/variable-fonts-info-site#105]
@khanniie pointed out today that https://variablefonts.typenetwork.com/examples/styles/roboto-instances-vs-interpolated#playground-experiment-unique-specimen-6 is setting `opsz` values but on `Roboto-min-VF.ttf` which doesn't have that axis. 

This was confusing as changing the value didn't do anything :)

**Comment by dberlow** [comment]
Hey Chris, can you just remove the opsz setting. I think this example is otherwise fine, as the point is that there are uses for the styles of Roboto in between the existing weights..
(I think this sample mistakenly started with Roboto Delta, which had opsz?)
